- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: 
    ansible.builtin.debug:
      msg: " course name is {{ Course }}, duration is : {{ Duration }}, thrainer is: {{ Trainer }}"